import type { Challenge } from "./challenges-store";

export const CHALLENGES_SEED: Challenge[] = [
  {
    id: "ENTERPRISE-ESENCIAL-C1",
    product: "enterprise",
    difficulty: "esencial",
    category: "Video",
    title: "30-Second Intro",
    description: "Record a 30-second video introducing yourself to a new client.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-ESENCIAL-C2",
    product: "enterprise",
    difficulty: "esencial",
    category: "Audio",
    title: "Voice Note Check-In",
    description: "Send a 1-minute voice note following up with a coworker about a pending task.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-ESENCIAL-C3",
    product: "enterprise",
    difficulty: "esencial",
    category: "Email",
    title: "Fix the Email",
    description: "Complete/fix an email with tone and grammar errors (you're given the draft).",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-ESENCIAL-C4",
    product: "enterprise",
    difficulty: "esencial",
    category: "Listening",
    title: "Quick Recap",
    description: "Listen to a short business audio clip and write down 3 key points.",
    video_url: "",
    premium: false,
    skill_tags: ["Listening", "Writing"],
  },
  {
    id: "ENTERPRISE-ESENCIAL-C5",
    product: "enterprise",
    difficulty: "esencial",
    category: "Email",
    title: "Out-of-Office Message",
    description: "Write your out-of-office auto-reply for a week of vacation.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-ESENCIAL-C6",
    product: "enterprise",
    difficulty: "esencial",
    category: "Audio",
    title: "Two Truths and a Task",
    description: "Record an audio describing 2 real tasks and 1 made-up one from your week; have someone guess which is fake.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-ESENCIAL-C7",
    product: "enterprise",
    difficulty: "esencial",
    category: "Email",
    title: "Meeting Invite",
    description: "Write the invite for a fictional meeting with a 3-point agenda.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-ESENCIAL-C8",
    product: "enterprise",
    difficulty: "esencial",
    category: "Reading",
    title: "Read & React",
    description: "Read a short business article and answer 3 comprehension questions.",
    video_url: "",
    premium: false,
    skill_tags: ["Reading"],
  },
  {
    id: "ENTERPRISE-ESENCIAL-C9",
    product: "enterprise",
    difficulty: "esencial",
    category: "Video",
    title: "Rate My Day",
    description: "Record a 1-minute video telling how your day at work went, using 5 verbs in the past tense.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-ESENCIAL-C10",
    product: "enterprise",
    difficulty: "esencial",
    category: "Audio",
    title: "Small Talk Starter",
    description: "Send an audio with 3 different ways to start small talk before a call.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-ESENCIAL-C11",
    product: "enterprise",
    difficulty: "esencial",
    category: "Written",
    title: "Price Check",
    description: "In writing, simulate asking the price of a service and requesting a simple discount.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-ESENCIAL-C12",
    product: "enterprise",
    difficulty: "esencial",
    category: "Written",
    title: "Thank You Note",
    description: "Write a thank-you note to a client or boss for something specific.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C1",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Pitch",
    title: "The Elevator Pitch",
    description: "Record a 60-second video with your personal or business pitch.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C2",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Audio",
    title: "Explain It Simply",
    description: "Record an audio explaining a work concept to someone who knows nothing about it.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C3",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Email",
    title: "Reschedule Diplomatically",
    description: "Write an email canceling and rescheduling an important meeting without sounding bad.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C4",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Negotiation",
    title: "Mini Negotiation",
    description: "Roleplay negotiating the price of a freelance service.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C5",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Networking",
    title: "Networking Opener",
    description: "Record an audio with 3 questions you'd ask to network at an event.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C6",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Email",
    title: "The Awkward Follow-Up",
    description: "Write a follow-up email to someone who hasn't replied to you in 2 weeks.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C7",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Video",
    title: "Explain the Chart",
    description: "You're given a simple chart; record yourself explaining it in 90 seconds.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C8",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Roleplay",
    title: "The Complaint Call",
    description: "Roleplay handling an angry client's complaint on the phone.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C9",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Business Case",
    title: "Compare Two Options",
    description: "Write an email comparing 2 vendors/options and recommending one.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C10",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Audio",
    title: "Podcast Summary",
    description: "Listen to a 5-minute business podcast and record yourself summarizing it in your own words.",
    video_url: "",
    premium: false,
    skill_tags: ["Listening", "Speaking"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C11",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Written",
    title: "The LinkedIn Post",
    description: "Write a LinkedIn post announcing a real or made-up professional achievement.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C12",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Leadership",
    title: "First Day Instructions",
    description: "Record a video explaining a new employee's first 3 tasks.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-INTERMEDIO-C13",
    product: "enterprise",
    difficulty: "intermedio",
    category: "Negotiation",
    title: "The Counteroffer",
    description: "In writing, respond to a job offer negotiating the salary.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C1",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Pitch",
    title: "Pitch to Win",
    description: "Record a 2-minute video pitching a business idea to \"investors\".",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C2",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Debate",
    title: "Debate: Remote vs. Office",
    description: "Prepare and record an audio defending a position in the remote vs. office debate.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C3",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Leadership",
    title: "The Difficult Conversation",
    description: "Roleplay giving a colleague constructive negative feedback.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C4",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Business Case",
    title: "Business Case Deep-Dive",
    description: "Read a short business case and write 3 strategic recommendations.",
    video_url: "",
    premium: false,
    skill_tags: ["Reading", "Writing"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C5",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Email",
    title: "Crisis Email",
    description: "Write the email you'd send to your clients if your service had a major outage today.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C6",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Persuasion",
    title: "Talk Me Out of It",
    description: "Record a video convincing someone NOT to cancel a project.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C7",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Roleplay",
    title: "The Panel Interview",
    description: "Roleplay answering 3 tough questions from a senior job interview.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C8",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Negotiation",
    title: "Negotiate the Deadline",
    description: "Roleplay negotiating a deadline extension with a demanding client.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C9",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Leadership",
    title: "Explain the Setback",
    description: "Record an audio explaining to your team why a project got delayed, without blaming anyone.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C10",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Networking",
    title: "Networking Recap",
    description: "After an imaginary event, write 3 follow-up emails to new contacts.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C11",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Negotiation",
    title: "The Skeptical Client",
    description: "Roleplay responding to the objections of a client who doubts your proposal.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C12",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Reading",
    title: "Read Between the Lines",
    description: "Read a passive-aggressive email, identify the real problem, and respond professionally.",
    video_url: "",
    premium: false,
    skill_tags: ["Reading", "Writing"],
  },
  {
    id: "ENTERPRISE-AVANZADO-C13",
    product: "enterprise",
    difficulty: "avanzado",
    category: "Video",
    title: "The 5-Minute Debrief",
    description: "Record a video summarizing the results of a (made-up) project to your boss.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-EXPERTO-C1",
    product: "enterprise",
    difficulty: "experto",
    category: "Negotiation",
    title: "High-Stakes Negotiation",
    description: "Roleplay a full negotiation (price, timeline, terms) with a \"difficult client\".",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-EXPERTO-C2",
    product: "enterprise",
    difficulty: "experto",
    category: "Debate",
    title: "Debate: Is Growth Always Good?",
    description: "Debate (live or recorded) defending an ethical stance on business growth.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-EXPERTO-C3",
    product: "enterprise",
    difficulty: "experto",
    category: "Pitch",
    title: "The Investor Q&A",
    description: "Roleplay: a 3-minute pitch followed by tough questions from \"investors\".",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-EXPERTO-C4",
    product: "enterprise",
    difficulty: "experto",
    category: "Written",
    title: "Crisis Press Statement",
    description: "Write the press statement you'd issue after a (made-up) reputation crisis at your company.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "ENTERPRISE-EXPERTO-C5",
    product: "enterprise",
    difficulty: "experto",
    category: "Leadership",
    title: "Lead the Difficult Announcement",
    description: "Roleplay: sensitively communicate a difficult business decision to your team.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-EXPERTO-C6",
    product: "enterprise",
    difficulty: "experto",
    category: "Business Case",
    title: "The Cross-Cultural Misunderstanding",
    description: "You're given a case of cultural clash in a meeting; record an audio explaining how you'd resolve it.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-EXPERTO-C7",
    product: "enterprise",
    difficulty: "experto",
    category: "Pitch",
    title: "Convince the Board",
    description: "Record a 3-minute video convincing a board of directors to approve your proposal.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-EXPERTO-C8",
    product: "enterprise",
    difficulty: "experto",
    category: "Video + Written",
    title: "The Public Apology",
    description: "Write and record a professional public apology video for a company mistake.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing", "Speaking"],
  },
  {
    id: "ENTERPRISE-EXPERTO-C9",
    product: "enterprise",
    difficulty: "experto",
    category: "Leadership",
    title: "Mediate the Conflict",
    description: "Roleplay mediating a conflict between two coworkers with opposing views.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-EXPERTO-C10",
    product: "enterprise",
    difficulty: "experto",
    category: "Video",
    title: "The Unscripted Interview",
    description: "Answer 5 interview questions on video that you don't know in advance.",
    video_url: "",
    premium: false,
    skill_tags: ["Listening", "Speaking"],
  },
  {
    id: "ENTERPRISE-EXPERTO-C11",
    product: "enterprise",
    difficulty: "experto",
    category: "Debate",
    title: "Defend Your Strategy",
    description: "Debate defending your business strategy against someone questioning it point by point.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "ENTERPRISE-EXPERTO-C12",
    product: "enterprise",
    difficulty: "experto",
    category: "Pitch",
    title: "The Global Expansion Pitch",
    description: "Record a 3-minute pitch proposing expanding a business into a new country, anticipating 3 objections.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-ESENCIAL-C1",
    product: "go",
    difficulty: "esencial",
    category: "Video",
    title: "My Day in 30 Seconds",
    description: "Record a 30-second video telling the most interesting thing that happened to you today.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-ESENCIAL-C2",
    product: "go",
    difficulty: "esencial",
    category: "Audio",
    title: "Voice Note to a Friend",
    description: "Send a 1-minute voice note inviting a friend to do something this weekend.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-ESENCIAL-C3",
    product: "go",
    difficulty: "esencial",
    category: "Written",
    title: "Fix the Text",
    description: "Fix a text message with common errors (you're given the draft).",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-ESENCIAL-C4",
    product: "go",
    difficulty: "esencial",
    category: "Listening",
    title: "Quick Recap",
    description: "Listen to a short audio clip (podcast/reel) and write 3 things you understood.",
    video_url: "",
    premium: false,
    skill_tags: ["Listening", "Writing"],
  },
  {
    id: "GO-ESENCIAL-C5",
    product: "go",
    difficulty: "esencial",
    category: "Written",
    title: "Caption This",
    description: "Write the perfect caption for a random photo (you're given the photo).",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-ESENCIAL-C6",
    product: "go",
    difficulty: "esencial",
    category: "Audio",
    title: "Two Truths and a Lie",
    description: "Record an audio with 2 real facts and 1 made-up one about you; have someone guess which is the lie.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-ESENCIAL-C7",
    product: "go",
    difficulty: "esencial",
    category: "Written",
    title: "Plan the Hangout",
    description: "Write the group chat message organizing a hangout with friends.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-ESENCIAL-C8",
    product: "go",
    difficulty: "esencial",
    category: "Reading",
    title: "Read & React",
    description: "Read a short social media post and give your opinion in 3 lines.",
    video_url: "",
    premium: false,
    skill_tags: ["Reading", "Writing"],
  },
  {
    id: "GO-ESENCIAL-C9",
    product: "go",
    difficulty: "esencial",
    category: "Video",
    title: "Rate My Day",
    description: "Record a 1-minute video telling how your day went, using 5 verbs in the past tense.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-ESENCIAL-C10",
    product: "go",
    difficulty: "esencial",
    category: "Audio",
    title: "Small Talk Starter",
    description: "Send an audio with 3 ways to break the ice with someone new.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-ESENCIAL-C11",
    product: "go",
    difficulty: "esencial",
    category: "Written",
    title: "Order Like a Local",
    description: "In writing, simulate ordering food at a new restaurant.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-ESENCIAL-C12",
    product: "go",
    difficulty: "esencial",
    category: "Written",
    title: "Say Thanks Right",
    description: "Write a thank-you message to someone who helped you.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-INTERMEDIO-C1",
    product: "go",
    difficulty: "intermedio",
    category: "Pitch",
    title: "My 60-Second Pitch",
    description: "Record a video presenting a personal project or hobby you're passionate about.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-INTERMEDIO-C2",
    product: "go",
    difficulty: "intermedio",
    category: "Audio",
    title: "Explain It Like I’m 5",
    description: "Record an audio explaining something you know well to someone who has no idea about it.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-INTERMEDIO-C3",
    product: "go",
    difficulty: "intermedio",
    category: "Written",
    title: "Cancel Plans Nicely",
    description: "Write a message canceling plans without being rude about it.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-INTERMEDIO-C4",
    product: "go",
    difficulty: "intermedio",
    category: "Debate",
    title: "Mini Debate: Coffee or Tea?",
    description: "Roleplay defending your preference on a random topic, with humor.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-INTERMEDIO-C5",
    product: "go",
    difficulty: "intermedio",
    category: "Audio",
    title: "Making a New Friend",
    description: "Record an audio with 3 questions you'd ask to get to know someone new.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-INTERMEDIO-C6",
    product: "go",
    difficulty: "intermedio",
    category: "Written",
    title: "The Awkward Follow-Up",
    description: "Write a follow-up message to someone who hasn't replied to you.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-INTERMEDIO-C7",
    product: "go",
    difficulty: "intermedio",
    category: "Video",
    title: "Explain the Meme",
    description: "You're given a meme; record yourself explaining it in 60 seconds.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-INTERMEDIO-C8",
    product: "go",
    difficulty: "intermedio",
    category: "Roleplay",
    title: "The Customer Service Call",
    description: "Roleplay resolving an order issue over the phone.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-INTERMEDIO-C9",
    product: "go",
    difficulty: "intermedio",
    category: "Written",
    title: "Compare Two Shows",
    description: "Write a review comparing 2 shows or movies.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-INTERMEDIO-C10",
    product: "go",
    difficulty: "intermedio",
    category: "Audio",
    title: "Podcast Summary",
    description: "Listen to a short podcast and record yourself summarizing it in your own words.",
    video_url: "",
    premium: false,
    skill_tags: ["Listening", "Speaking"],
  },
  {
    id: "GO-INTERMEDIO-C11",
    product: "go",
    difficulty: "intermedio",
    category: "Written",
    title: "The Social Media Post",
    description: "Write a post announcing something good that happened to you.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-INTERMEDIO-C12",
    product: "go",
    difficulty: "intermedio",
    category: "Video",
    title: "Teach Me Something",
    description: "Record a video teaching a hobby or trick you know how to do.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-INTERMEDIO-C13",
    product: "go",
    difficulty: "intermedio",
    category: "Negotiation",
    title: "Negotiate the Price",
    description: "Roleplay negotiating the price of something at a market/secondhand sale.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-AVANZADO-C1",
    product: "go",
    difficulty: "avanzado",
    category: "Pitch",
    title: "Pitch Your Dream Project",
    description: "Record a 2-minute video pitching a personal project idea to imaginary \"investors\".",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-AVANZADO-C2",
    product: "go",
    difficulty: "avanzado",
    category: "Debate",
    title: "Debate: Is Social Media Good or Bad?",
    description: "Prepare and record an audio defending a position.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-AVANZADO-C3",
    product: "go",
    difficulty: "avanzado",
    category: "Roleplay",
    title: "The Difficult Conversation",
    description: "Roleplay telling a friend something awkward in a kind way.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-AVANZADO-C4",
    product: "go",
    difficulty: "avanzado",
    category: "Written",
    title: "Movie Review Deep-Dive",
    description: "Write 3 reasons why you would or wouldn't recommend a movie or show.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-AVANZADO-C5",
    product: "go",
    difficulty: "avanzado",
    category: "Written",
    title: "The Apology Text",
    description: "Write the message you'd send after messing up with someone.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-AVANZADO-C6",
    product: "go",
    difficulty: "avanzado",
    category: "Persuasion",
    title: "Talk Me Out of It",
    description: "Record a video convincing someone NOT to cancel a planned trip.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-AVANZADO-C7",
    product: "go",
    difficulty: "avanzado",
    category: "Roleplay",
    title: "The Random Interview",
    description: "Roleplay answering 3 unexpected questions from a podcast interview.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-AVANZADO-C8",
    product: "go",
    difficulty: "avanzado",
    category: "Negotiation",
    title: "Negotiate the Roommate Rules",
    description: "Roleplay negotiating house rules with a roommate.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-AVANZADO-C9",
    product: "go",
    difficulty: "avanzado",
    category: "Audio",
    title: "Explain the Awkward Situation",
    description: "Record an audio explaining why you were late to something important, without lame excuses.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-AVANZADO-C10",
    product: "go",
    difficulty: "avanzado",
    category: "Networking",
    title: "Networking at a Party",
    description: "After an imaginary event, write 2 follow-up messages to new people you met.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-AVANZADO-C11",
    product: "go",
    difficulty: "avanzado",
    category: "Negotiation",
    title: "The Skeptical Friend",
    description: "Roleplay convincing a skeptical friend to join a plan.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-AVANZADO-C12",
    product: "go",
    difficulty: "avanzado",
    category: "Reading",
    title: "Read Between the Lines",
    description: "Read a passive-aggressive message, identify the real problem, and respond well.",
    video_url: "",
    premium: false,
    skill_tags: ["Reading", "Writing"],
  },
  {
    id: "GO-AVANZADO-C13",
    product: "go",
    difficulty: "avanzado",
    category: "Video",
    title: "The 5-Minute Life Update",
    description: "Record a video telling a faraway friend how your life has been lately.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-EXPERTO-C1",
    product: "go",
    difficulty: "experto",
    category: "Negotiation",
    title: "High-Stakes Negotiation",
    description: "Roleplay negotiating something important (rent, a used car, etc.) with a difficult person.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-EXPERTO-C2",
    product: "go",
    difficulty: "experto",
    category: "Debate",
    title: "Debate: Is Ambition Overrated?",
    description: "Debate defending a philosophical stance on success or ambition.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-EXPERTO-C3",
    product: "go",
    difficulty: "experto",
    category: "Pitch",
    title: "The Q&A After Your Pitch",
    description: "Roleplay: present your project idea and answer tough questions.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-EXPERTO-C4",
    product: "go",
    difficulty: "experto",
    category: "Written",
    title: "The Public Apology Post",
    description: "Write the post you'd publish after a (made-up) public mistake.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "GO-EXPERTO-C5",
    product: "go",
    difficulty: "experto",
    category: "Roleplay",
    title: "Deliver Hard News Kindly",
    description: "Roleplay: sensitively deliver difficult news to a loved one.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-EXPERTO-C6",
    product: "go",
    difficulty: "experto",
    category: "Business Case",
    title: "The Cultural Misunderstanding",
    description: "You're given a case of cultural clash on a trip; record an audio explaining how you'd resolve it.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-EXPERTO-C7",
    product: "go",
    difficulty: "experto",
    category: "Video",
    title: "Convince Your Family",
    description: "Record a 3-minute video convincing your family of an important life decision.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-EXPERTO-C8",
    product: "go",
    difficulty: "experto",
    category: "Video",
    title: "The Public Apology (Video)",
    description: "Record a sincere public apology video for a (made-up) mistake.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-EXPERTO-C9",
    product: "go",
    difficulty: "experto",
    category: "Roleplay",
    title: "Mediate the Friend Group Drama",
    description: "Roleplay mediating a conflict between two friends with opposing views.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-EXPERTO-C10",
    product: "go",
    difficulty: "experto",
    category: "Video",
    title: "The Unscripted Interview",
    description: "Answer 5 interview questions on video that you don't know in advance (have someone ask you).",
    video_url: "",
    premium: false,
    skill_tags: ["Listening", "Speaking"],
  },
  {
    id: "GO-EXPERTO-C11",
    product: "go",
    difficulty: "experto",
    category: "Debate",
    title: "Defend an Unpopular Opinion",
    description: "Debate defending an unpopular opinion against someone who challenges it.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "GO-EXPERTO-C12",
    product: "go",
    difficulty: "experto",
    category: "Pitch",
    title: "The Big Move Pitch",
    description: "Record a 3-minute pitch proposing a move to another country/city, anticipating 3 objections from your family.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-ESENCIAL-C1",
    product: "international",
    difficulty: "esencial",
    category: "Roleplay",
    title: "Airport Arrival",
    description: "Roleplay going through immigration explaining the reason for your trip.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-ESENCIAL-C2",
    product: "international",
    difficulty: "esencial",
    category: "Audio",
    title: "Voice Note Home",
    description: "Send an audio telling your family how your first week is going.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-ESENCIAL-C3",
    product: "international",
    difficulty: "esencial",
    category: "Written",
    title: "Fix the Form",
    description: "Fix a form with common errors (you're given the draft).",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "INTERNATIONAL-ESENCIAL-C4",
    product: "international",
    difficulty: "esencial",
    category: "Listening",
    title: "Quick Recap",
    description: "Listen to an airport/station announcement and write 3 things you understood.",
    video_url: "",
    premium: false,
    skill_tags: ["Listening", "Writing"],
  },
  {
    id: "INTERNATIONAL-ESENCIAL-C5",
    product: "international",
    difficulty: "esencial",
    category: "Written",
    title: "Order at a Drive-Thru",
    description: "In writing, simulate a quick order at a drive-thru.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "INTERNATIONAL-ESENCIAL-C6",
    product: "international",
    difficulty: "esencial",
    category: "Audio",
    title: "Two Truths and a Lie (New City Edition)",
    description: "Record an audio with 2 real facts and 1 made-up one about your new city.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-ESENCIAL-C7",
    product: "international",
    difficulty: "esencial",
    category: "Video",
    title: "Ask for Directions",
    description: "Record a video (roleplay) asking someone on the street for directions.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-ESENCIAL-C8",
    product: "international",
    difficulty: "esencial",
    category: "Reading",
    title: "Read & React",
    description: "Read a rental listing and answer 3 comprehension questions.",
    video_url: "",
    premium: false,
    skill_tags: ["Reading", "Writing"],
  },
  {
    id: "INTERNATIONAL-ESENCIAL-C9",
    product: "international",
    difficulty: "esencial",
    category: "Video",
    title: "Rate My Day",
    description: "Record a 1-minute video telling how your first day in a new place went.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-ESENCIAL-C10",
    product: "international",
    difficulty: "esencial",
    category: "Audio",
    title: "Small Talk Starter",
    description: "Send an audio with 3 ways to start small talk with a new neighbor.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-ESENCIAL-C11",
    product: "international",
    difficulty: "esencial",
    category: "Written",
    title: "Grocery Store Checklist",
    description: "Write a grocery list and how you'd ask for help finding something.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "INTERNATIONAL-ESENCIAL-C12",
    product: "international",
    difficulty: "esencial",
    category: "Written",
    title: "Say Thanks to a Stranger",
    description: "Write a thank-you note to someone who helped you when you got lost.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C1",
    product: "international",
    difficulty: "intermedio",
    category: "Video",
    title: "My Story in 60 Seconds",
    description: "Record a video telling why you decided to move to/live in another country.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C2",
    product: "international",
    difficulty: "intermedio",
    category: "Audio",
    title: "Explain a Custom From Home",
    description: "Record an audio explaining a custom from your country to someone from a different culture.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C3",
    product: "international",
    difficulty: "intermedio",
    category: "Written",
    title: "Reschedule an Appointment",
    description: "Write a message rescheduling a doctor's appointment.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C4",
    product: "international",
    difficulty: "intermedio",
    category: "Negotiation",
    title: "Mini Negotiation: The Landlord Call",
    description: "Roleplay negotiating a repair with your landlord.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C5",
    product: "international",
    difficulty: "intermedio",
    category: "Audio",
    title: "Making a New Friend Abroad",
    description: "Record an audio with 3 questions to get to know someone new in your new city.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C6",
    product: "international",
    difficulty: "intermedio",
    category: "Written",
    title: "The Awkward Follow-Up",
    description: "Write a follow-up message to a coworker who hasn't replied to you.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C7",
    product: "international",
    difficulty: "intermedio",
    category: "Video",
    title: "Explain a Bill",
    description: "You're given a confusing bill; record yourself explaining what you understand from it.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C8",
    product: "international",
    difficulty: "intermedio",
    category: "Roleplay",
    title: "The Customer Service Call",
    description: "Roleplay resolving an internet service issue over the phone.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C9",
    product: "international",
    difficulty: "intermedio",
    category: "Written",
    title: "Compare Two Apartments",
    description: "Write comparing 2 rental options and which one you'd choose.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C10",
    product: "international",
    difficulty: "intermedio",
    category: "Audio",
    title: "Podcast Summary",
    description: "Listen to a short podcast about living abroad and summarize it in an audio recording.",
    video_url: "",
    premium: false,
    skill_tags: ["Listening", "Speaking"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C11",
    product: "international",
    difficulty: "intermedio",
    category: "Written",
    title: "The Social Media Update",
    description: "Write a post telling your family and friends how your new life is going.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C12",
    product: "international",
    difficulty: "intermedio",
    category: "Video",
    title: "Teach Me a Local Custom",
    description: "Record a video explaining a local custom you learned.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-INTERMEDIO-C13",
    product: "international",
    difficulty: "intermedio",
    category: "Negotiation",
    title: "Negotiate a Used Car Price",
    description: "Roleplay negotiating the price of a used car.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C1",
    product: "international",
    difficulty: "avanzado",
    category: "Pitch",
    title: "Pitch Yourself for a Job",
    description: "Record a 2-minute video with your pitch for a job interview.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C2",
    product: "international",
    difficulty: "avanzado",
    category: "Debate",
    title: "Debate: Is It Worth Moving Abroad?",
    description: "Prepare and record an audio defending a position.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C3",
    product: "international",
    difficulty: "avanzado",
    category: "Roleplay",
    title: "The Difficult Conversation With Family",
    description: "Roleplay explaining to your family why you decided to stay abroad longer.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C4",
    product: "international",
    difficulty: "avanzado",
    category: "Business Case",
    title: "Housing Case Deep-Dive",
    description: "Read a short rental contract and write 3 things you'd check before signing.",
    video_url: "",
    premium: false,
    skill_tags: ["Reading", "Writing"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C5",
    product: "international",
    difficulty: "avanzado",
    category: "Email",
    title: "Emergency Email",
    description: "Write the email you'd send to work if you had a medical emergency today.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C6",
    product: "international",
    difficulty: "avanzado",
    category: "Persuasion",
    title: "Talk Me Out of It",
    description: "Record a video convincing a friend NOT to go back to their country yet.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C7",
    product: "international",
    difficulty: "avanzado",
    category: "Roleplay",
    title: "The Immigration Interview",
    description: "Roleplay answering 3 tough questions from an immigration interview.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C8",
    product: "international",
    difficulty: "avanzado",
    category: "Negotiation",
    title: "Negotiate the Deadline",
    description: "Roleplay negotiating a deadline extension for a paperwork process.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C9",
    product: "international",
    difficulty: "avanzado",
    category: "Audio",
    title: "Explain a Misunderstanding at Work",
    description: "Record an audio explaining a cultural misunderstanding to your boss, without blaming anyone.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C10",
    product: "international",
    difficulty: "avanzado",
    category: "Networking",
    title: "Networking Recap",
    description: "After an imaginary event, write 2 follow-up emails to new contacts.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C11",
    product: "international",
    difficulty: "avanzado",
    category: "Negotiation",
    title: "The Skeptical Landlord",
    description: "Roleplay convincing a skeptical landlord to rent to you without local credit history.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C12",
    product: "international",
    difficulty: "avanzado",
    category: "Reading",
    title: "Read Between the Lines",
    description: "Read an ambiguous message from your boss, identify the real problem, and respond professionally.",
    video_url: "",
    premium: false,
    skill_tags: ["Reading", "Writing"],
  },
  {
    id: "INTERNATIONAL-AVANZADO-C13",
    product: "international",
    difficulty: "avanzado",
    category: "Video",
    title: "The 5-Minute Life Update",
    description: "Record a video telling your family how your life has been in the new country.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-EXPERTO-C1",
    product: "international",
    difficulty: "experto",
    category: "Negotiation",
    title: "High-Stakes Negotiation",
    description: "Roleplay negotiating a full job contract (salary, benefits, schedule).",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-EXPERTO-C2",
    product: "international",
    difficulty: "experto",
    category: "Debate",
    title: "Debate: Should Everyone Learn a Second Language?",
    description: "Debate defending a position.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-EXPERTO-C3",
    product: "international",
    difficulty: "experto",
    category: "Roleplay",
    title: "The Visa Interview Q&A",
    description: "Roleplay: answer tough questions from a visa/residency interview.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-EXPERTO-C4",
    product: "international",
    difficulty: "experto",
    category: "Written",
    title: "Crisis Message Home",
    description: "Write the message you'd send your family if something went wrong (hypothetically) with your immigration process.",
    video_url: "",
    premium: false,
    skill_tags: ["Writing"],
  },
  {
    id: "INTERNATIONAL-EXPERTO-C5",
    product: "international",
    difficulty: "experto",
    category: "Roleplay",
    title: "Deliver Hard News to Family",
    description: "Roleplay: sensitively communicate a difficult decision to your family.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-EXPERTO-C6",
    product: "international",
    difficulty: "experto",
    category: "Business Case",
    title: "The Cross-Cultural Misunderstanding",
    description: "You're given a case of cultural clash at work; record an audio explaining how you'd resolve it.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-EXPERTO-C7",
    product: "international",
    difficulty: "experto",
    category: "Pitch",
    title: "Convince the Neighborhood Board",
    description: "Record a 3-minute video convincing a neighborhood association to approve your request.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-EXPERTO-C8",
    product: "international",
    difficulty: "experto",
    category: "Video",
    title: "The Public Apology",
    description: "Record a sincere public apology video for a (made-up) cultural misunderstanding.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-EXPERTO-C9",
    product: "international",
    difficulty: "experto",
    category: "Roleplay",
    title: "Mediate a Cultural Conflict",
    description: "Roleplay mediating a conflict between two coworkers from different cultures.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-EXPERTO-C10",
    product: "international",
    difficulty: "experto",
    category: "Video",
    title: "The Unscripted Interview",
    description: "Answer 5 interview questions on video that you don't know in advance.",
    video_url: "",
    premium: false,
    skill_tags: ["Listening", "Speaking"],
  },
  {
    id: "INTERNATIONAL-EXPERTO-C11",
    product: "international",
    difficulty: "experto",
    category: "Debate",
    title: "Defend Your Decision to Stay",
    description: "Debate defending your decision to stay in the new country against someone who questions it.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
  {
    id: "INTERNATIONAL-EXPERTO-C12",
    product: "international",
    difficulty: "experto",
    category: "Pitch",
    title: "The Citizenship Pitch",
    description: "Record a 3-minute pitch explaining why you want citizenship/permanent residency.",
    video_url: "",
    premium: false,
    skill_tags: ["Speaking"],
  },
];